version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [app-net]

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
      - "${KAFKA_EXTERNAL_PORT:-9094}:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:${KAFKA_EXTERNAL_PORT:-9094}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks: [app-net]

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.2
    container_name: kafdrop
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32m -Xmx128m"
    ports:
      - "9000:9000"
    networks: [app-net]

  propostaservice:
    build:
      context: ./PropostaService
      dockerfile: Dockerfile
    container_name: propostaservice
    environment:
      ASPNETCORE_URLS: http://+:${PROPOSTA_PORT}
      ConnectionStrings__MySql: "server=mysql;port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}"
      Kafka__BootstrapServers: "kafka:9092"
    ports:
      - "${PROPOSTA_PORT}:${PROPOSTA_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks: [app-net]

  contratacaoservice:
    build:
      context: ./ContratacaoService
      dockerfile: Dockerfile
    container_name: contratacaoservice
    environment:
      ASPNETCORE_URLS: http://+:${CONTRATACAO_PORT}
      ConnectionStrings__MySql: "server=mysql;port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}"
      Kafka__BootstrapServers: "kafka:9092"
    ports:
      - "${CONTRATACAO_PORT}:${CONTRATACAO_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks: [app-net]

networks:
  app-net:

volumes:
  mysql_data:
  kafka_data:
